import sqlite3 from "sqlite3";
import { promisify } from "util";
import path from "path";
import { createClient } from "@supabase/supabase-js";

// Check for Supabase Environment Variables
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;
const isSupabaseEnabled = !!(supabaseUrl && supabaseKey);

let supabase = null;
let db = null;
let dbRun, dbAll, dbGet;

if (isSupabaseEnabled) {
  supabase = createClient(supabaseUrl, supabaseKey);
  console.log("=================================================");
  console.log(" CLIENTAGENT: Cloud Database Active (Supabase Mode)");
  console.log("=================================================");
} else {
  const dbFile = path.resolve("./database.db");
  db = new sqlite3.Database(dbFile);
  dbRun = promisify(db.run.bind(db));
  dbAll = promisify(db.all.bind(db));
  dbGet = promisify(db.get.bind(db));
  console.log("=================================================");
  console.log(" CLIENTAGENT: Local Database Active (SQLite Mode)");
  console.log("=================================================");
}

// SQL Schema for copy-paste in Supabase SQL editor
const SUPABASE_SCHEMA_HELP = `
-- COPY & RUN THIS IN YOUR SUPABASE SQL EDITOR TO SETUP TABLES:

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT,
  name TEXT,
  contact TEXT,
  email TEXT,
  score INTEGER,
  reason TEXT,
  action TEXT,
  status TEXT DEFAULT 'new',
  stage TEXT DEFAULT 'First Contact',
  value TEXT DEFAULT '',
  "lastActivity" TEXT DEFAULT 'Just now',
  avatar TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  subject TEXT,
  body TEXT,
  sent_at TEXT,
  opened_at TEXT,
  replied_at TEXT
);

CREATE TABLE IF NOT EXISTS chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT,
  text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
`;

// Initialize Database Tables
export async function initDb() {
  if (isSupabaseEnabled) {
    console.log("Ensuring default cloud settings exist in Supabase...");
    try {
      const defaultSettings = [
        { key: "niche", value: "Graphic Design NGO Uganda" },
        { key: "daily_quota", value: "10" },
        { key: "anthropic_api_key", value: "" },
        { key: "sendgrid_api_key", value: "" },
        { key: "smtp_host", value: "" },
        { key: "smtp_port", value: "587" },
        { key: "smtp_user", value: "" },
        { key: "smtp_pass", value: "" },
        { key: "email_sender", value: "" },
        { key: "email_sender_name", value: "Henry | BrandCraft" },
        { key: "auto_send", value: "false" }
      ];

      // Upsert default settings if they aren't there
      for (const s of defaultSettings) {
        const { data } = await supabase.from("settings").select("key").eq("key", s.key);
        if (!data || data.length === 0) {
          await supabase.from("settings").insert(s);
        }
      }
    } catch (e) {
      console.warn(" Supabase setup warning: Make sure you ran the SQL Editor setup.");
      console.log(SUPABASE_SCHEMA_HELP);
    }
    return;
  }

  // SQLite Initialization
  await dbRun(`
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT
    )
  `);

  await dbRun(`
    CREATE TABLE IF NOT EXISTS leads (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      platform TEXT,
      name TEXT,
      contact TEXT,
      email TEXT,
      score INTEGER,
      reason TEXT,
      action TEXT,
      status TEXT DEFAULT 'new',
      stage TEXT DEFAULT 'First Contact',
      value TEXT DEFAULT '',
      lastActivity TEXT DEFAULT 'Just now',
      avatar TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await dbRun(`
    CREATE TABLE IF NOT EXISTS email_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      lead_id INTEGER,
      subject TEXT,
      body TEXT,
      sent_at TEXT,
      opened_at TEXT,
      replied_at TEXT
    )
  `);

  await dbRun(`
    CREATE TABLE IF NOT EXISTS chat_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      role TEXT,
      text TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);

  const defaultSettings = [
    { key: "niche", value: "Graphic Design NGO Uganda" },
    { key: "daily_quota", value: "10" },
    { key: "anthropic_api_key", value: "" },
    { key: "sendgrid_api_key", value: "" },
    { key: "smtp_host", value: "" },
    { key: "smtp_port", value: "587" },
    { key: "smtp_user", value: "" },
    { key: "smtp_pass", value: "" },
    { key: "email_sender", value: "" },
    { key: "email_sender_name", value: "Henry | BrandCraft" },
    { key: "auto_send", value: "false" }
  ];

  for (const s of defaultSettings) {
    await dbRun(`INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)`, [s.key, s.value]);
  }



  const chatCount = await dbGet(`SELECT count(*) as count FROM chat_history`);
  if (chatCount.count === 0) {
    await dbRun(`
      INSERT INTO chat_history (role, text)
      VALUES (?, ?)
    `, ["agent", "Hello Henry! I'm your ClientAgent. I'm connected to your local database. What can I help you build today?"]);
  }
}

// Settings API
export async function getSettings() {
  if (isSupabaseEnabled) {
    const { data, error } = await supabase.from("settings").select("*");
    if (error) throw error;
    const config = {};
    data.forEach(r => { config[r.key] = r.value; });
    return config;
  }

  const rows = await dbAll(`SELECT * FROM settings`);
  const config = {};
  rows.forEach(r => { config[r.key] = r.value; });
  return config;
}

export async function updateSetting(key, value) {
  if (isSupabaseEnabled) {
    const { error } = await supabase.from("settings").upsert({ key, value });
    if (error) throw error;
    return;
  }
  await dbRun(`INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)`, [key, value]);
}

// Leads API
export async function getAllLeads() {
  if (isSupabaseEnabled) {
    const { data, error } = await supabase.from("leads").select("*").order("score", { ascending: false }).order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  }
  return await dbAll(`SELECT * FROM leads ORDER BY score DESC, created_at DESC`);
}

export async function addLead(lead) {
  if (isSupabaseEnabled) {
    const cleanLead = {
      platform: lead.platform || "Web",
      name: lead.name,
      contact: lead.contact || "Unknown Contact",
      email: lead.email || "",
      score: lead.score || 50,
      reason: lead.reason || "",
      action: lead.action || "Evaluate",
      status: lead.status || "new",
      stage: lead.stage || "First Contact",
      value: lead.value || "",
      avatar: lead.avatar || "#7C3AED"
    };
    const { data, error } = await supabase.from("leads").insert(cleanLead).select("id").single();
    if (error) throw error;
    return data.id;
  }

  await dbRun(`
    INSERT INTO leads (platform, name, contact, email, score, reason, action, status, stage, value, avatar)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `, [
    lead.platform || "Web",
    lead.name,
    lead.contact || "Unknown Contact",
    lead.email || "",
    lead.score || 50,
    lead.reason || "",
    lead.action || "Evaluate",
    lead.status || "new",
    lead.stage || "First Contact",
    lead.value || "",
    lead.avatar || "#7C3AED"
  ]);
  
  const row = await dbGet(`SELECT last_insert_rowid() as id`);
  return row.id;
}

export async function updateLeadStatus(id, status, stage, value) {
  if (isSupabaseEnabled) {
    const updateObj = { status };
    if (stage !== undefined) updateObj.stage = stage;
    if (value !== undefined) updateObj.value = value;
    updateObj.lastActivity = "Updated just now";

    const { error } = await supabase.from("leads").update(updateObj).eq("id", id);
    if (error) throw error;
    return;
  }

  if (stage !== undefined && value !== undefined) {
    await dbRun(`UPDATE leads SET status = ?, stage = ?, value = ?, lastActivity = 'Updated just now' WHERE id = ?`, [status, stage, value, id]);
  } else if (stage !== undefined) {
    await dbRun(`UPDATE leads SET status = ?, stage = ?, lastActivity = 'Updated just now' WHERE id = ?`, [status, stage, id]);
  } else {
    await dbRun(`UPDATE leads SET status = ?, lastActivity = 'Updated just now' WHERE id = ?`, [status, id]);
  }
}

export async function updateLead(id, data) {
  if (isSupabaseEnabled) {
    const { error } = await supabase.from("leads").update(data).eq("id", id);
    if (error) throw error;
    return;
  }

  const fields = [];
  const values = [];
  Object.keys(data).forEach(k => {
    fields.push(`${k} = ?`);
    values.push(data[k]);
  });
  values.push(id);
  await dbRun(`UPDATE leads SET ${fields.join(", ")} WHERE id = ?`, values);
}

// Email Logs API
export async function logEmail(leadId, subject, body) {
  if (isSupabaseEnabled) {
    const { data, error } = await supabase.from("email_logs").insert({
      lead_id: leadId,
      subject,
      body,
      sent_at: new Date().toISOString()
    }).select("id").single();
    if (error) throw error;
    return data.id;
  }

  await dbRun(`
    INSERT INTO email_logs (lead_id, subject, body, sent_at)
    VALUES (?, ?, ?, datetime('now'))
  `, [leadId, subject, body]);
  const row = await dbGet(`SELECT last_insert_rowid() as id`);
  return row.id;
}

export async function getEmailLogs() {
  if (isSupabaseEnabled) {
    // In Supabase we select the log and join the lead details
    const { data, error } = await supabase
      .from("email_logs")
      .select("*, leads(name, email)")
      .order("id", { ascending: false });
      
    if (error) throw error;
    // Flatten result to match SQLite format
    return data.map(d => ({
      ...d,
      lead_name: d.leads?.name || "Unknown",
      lead_email: d.leads?.email || ""
    }));
  }

  return await dbAll(`
    SELECT e.*, l.name as lead_name, l.email as lead_email
    FROM email_logs e
    JOIN leads l ON e.lead_id = l.id
    ORDER BY e.id DESC
  `);
}

export async function markEmailOpened(logId) {
  if (isSupabaseEnabled) {
    const { error } = await supabase.from("email_logs").update({ opened_at: new Date().toISOString() }).eq("id", logId);
    if (error) throw error;
    return;
  }
  await dbRun(`UPDATE email_logs SET opened_at = datetime('now') WHERE id = ?`, [logId]);
}

export async function markEmailReplied(logId) {
  if (isSupabaseEnabled) {
    const { error } = await supabase.from("email_logs").update({ replied_at: new Date().toISOString() }).eq("id", logId);
    if (error) throw error;
    return;
  }
  await dbRun(`UPDATE email_logs SET replied_at = datetime('now') WHERE id = ?`, [logId]);
}

// Chat API
export async function getChatHistory() {
  if (isSupabaseEnabled) {
    const { data, error } = await supabase.from("chat_history").select("*").order("id", { ascending: true });
    if (error) throw error;
    return data;
  }
  return await dbAll(`SELECT * FROM chat_history ORDER BY id ASC`);
}

export async function addChatMessage(role, text) {
  if (isSupabaseEnabled) {
    const { error } = await supabase.from("chat_history").insert({ role, text });
    if (error) throw error;
    return;
  }
  await dbRun(`INSERT INTO chat_history (role, text) VALUES (?, ?)`, [role, text]);
}
